repos:

# Source: https://github.com/ACED-IDP/gen3_util/blob/development/.pre-commit-config.yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
      args: [--maxkb=5120]
    - id: check-case-conflict #Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
    - id: check-shebang-scripts-are-executable
    - id: check-yaml
    - id: detect-private-key # detect-private-key is not in repo
    - id: mixed-line-ending
    - id: trailing-whitespace
